### ISSUE TITLE
Problem with running hello world!

### ISSUE THREAD

**Issue by sharkbait2** [loop-lang/loop#29]
Hi, new to github (sorry if this issue poorly written). I try to fork and and compile this project and run the hello world example but its not printing hello world. Instead the source files is printed as separate words. Need help to run the hello world file
```
C:\github\loop>loop.exe examples/example.loop
59:import
2:Std
18:.
2:Console
21:;
60:fn
2:Main
22:(
23:)
24:{
2:Console
18:.
2:Writeln
22:(
4:'Hello World'
23:)
25:}
Tokenization was ←[92;1mSuccessful←[0;1m (21 tokens found)
```

**Comment by AliChraghi** [comment]
don't worry this means that works fine.
we currently just finished tokenization and 0.0.1 not released :)
